name       : qdirstat
version    : '1.5'
release    : 2
source     :
    - https://github.com/shundhammer/qdirstat/archive/1.5.tar.gz : 5de21fb1ccc9f4df29b2969aa652237b4430e2cfbe37f6eda088482ed44bdbf5
license    : GPL-2.0-only
component  : desktop
summary    : QDirStat is a graphical application to show where your disk space has gone and to help you to clean it up
description: |
    graphical disk usage display with cleanup facilities
    QDirStat (Qt Directory Statistics) is a small utility program that sums
    up disk usage for directory trees, very much like the Unix 'du' command.
    It displays the disk space used up by a directory tree, both numerically
    and graphically.  It is network transparent (i.e., you can use it to sum
    up FTP servers), and comes with predefined and user configurable cleanup
    actions.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
rundeps    :
    - perl-uri # for qdirstat-cache-writer
setup      : |
    %qmake INSTALL_PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 man/qdirstat.1 $installdir/usr/share/man/man1/qdirstat.1
