name       : qdirstat
version    : '1.7'
release    : 5
source     :
    - https://github.com/shundhammer/qdirstat/archive/1.7.tar.gz : 9a8ec22a19290794147f727bca27deb7e02b4d9c537deb2fd0d3e647621f8c4a
homepage   : https://github.com/shundhammer/qdirstat
license    : GPL-2.0-only
component  : desktop
summary    : QDirStat is a graphical application to show where your disk space has gone and to help you to clean it up
description: |
    graphical disk usage display with cleanup facilities. QDirStat (Qt Directory Statistics) is a small utility program that sums up disk usage for directory trees, very much like the Unix 'du' command. It displays the disk space used up by a directory tree, both numerically and graphically. It is network transparent (i.e., you can use it to sum up FTP servers), and comes with predefined and user configurable cleanup actions.
builddeps  :
    - pkgconfig(Qt5Core)
rundeps    :
    - perl-uri # for qdirstat-cache-writer
setup      : |
    %qmake INSTALL_PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 man/qdirstat.1 $installdir/usr/share/man/man1/qdirstat.1
